version: "3.1"

services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - postgresql
    ports:
      - 8088:8080
    links:
      - postgresql:localhost
